// Generated by CoffeeScript 1.8.0
(function() {
  var define_controller;

  define('cars', function() {
    var user_plugin;
    return user_plugin = {
      name: 'cars',
      anchor: '#/cars',
      title: 'Cars Management',
      type: 'plugin',
      icon: 'icon-list',
      init: function() {
        var self;
        self = this;
        console.log('init');
        return foundry.model("Car", ["name", "price", "car_type", "rate", "amount", "image", "thumb", "detail", "created_at", "modified_at"], function() {
          foundry.initialized(self.name);
          return define_controller();
        });
      }
    };
  });

  define_controller = function() {
    return angular.module('foundry').controller('CarsController', [
      '$scope', '$foundry', function($scope, $foundry) {
        var car_model, file_module;
        window.scope = $scope;
        car_model = foundry.load_model("Car");
        file_module = foundry.load('document');
        $scope.current = {};
        $scope.upload = function() {
          var spinner;
          spinner = $foundry.spinner({
            type: 'loading',
            text: 'Uploading '
          });
          Nimbus.Binary.upload_file($scope.choosed_file, function(file) {
            file_module.set(file._file.id, file._file);
            $scope.uploaded = {
              thumb: file._file.thumbnailLink,
              name: file.name,
              link: file.directlink
            };
            $scope.current.image = $scope.uploaded.link;
            $scope.current.thumb = $scope.uploaded.thumb;
            $scope.choosed_file = null;
            spinner.hide();
            return $scope.$apply();
          });
        };
        $scope.add = function() {
          var created, now, to_save;
          if ($scope.current.name && $scope.current.price && $scope.current.car_type && $scope.current.rate && $scope.current.amount && $scope.current.image && $scope.current.thumb && $scope.current.detail) {
            to_save = $scope.current;
            now = new Date().getTime();
            to_save.created_at = now;
            to_save.modified_at = now;
            created = car_model.create(to_save);
            $scope.mode = true;
            $scope.old = created;
            return $scope.load();
          } else {
            return alert("Please make sure every filed is filled.");
          }
        };
        $scope.load = function() {
          return $scope.cars = car_model.all();
        };
        return $scope.load();
      }
    ]);
  };

}).call(this);
