// Generated by CoffeeScript 1.7.1
(function() {
  if (localStorage["version"] == null) {
    localStorage["version"] = "google";
    window.location.reload();
  }

  foundry.angular.dependency = [];
  
  window.app_config = {}
  window.app_config.supported_field = {
    '_field_switch': ["on_value", "off_value", "default_value"],
    '_field_text_input': ["default_value", "required"],
    '_field_text_area': ["default_value", "required"],
    '_field_rate': ["default_value", "max_rate", "required"],
    '_field_number_input': ["default_value", "max_value", "min_value", "required"],
    '_field_image': ["required"]
  }
  window.app_config.supported_field_setting = {
    '_field_switch': ["Switch"],
    '_field_text_input': ["Text Input"],
    '_field_text_area': ["Text Area"],
    '_field_rate': ["Rate"],
    '_field_number_input': ["Nimber Input"],
    '_field_image': ["Image"]
  }
  window.app_config.common_fields = ["model_belonged_to", "field_name"]
  window.app_config.show_in_detail = {
    '_field_text_area' : 'right',
    '_field_image': 'left'
  }
  define('config', function() {
    var config;
    config = {};
    config.appName = 'Foundry';
    config.plugins = {
      user: 'core/plugins/user',
      workspace: 'core/plugins/workspace',
      //document: 'core/plugins/document',
      model_editor : 'app/plugins/model_editor',
      model_manager : 'app/plugins/model_manager'
    };
    return config;
  });

  foundry.load_plugins();

  Nimbus.Auth.setup({
    'GDrive': {
      'app_id' : '176681637100',
      'key': '176681637100-139utdaqo9ajoiudphscok1a9krsbc0c.apps.googleusercontent.com',
      "scope": "openid https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/plus.me"
    },
    "app_name": "Cars Management",
    'synchronous': false
  });

  Nimbus.Auth.authorized_callback = function() {
    $("#login_buttons").addClass("redirect");
  };

  foundry.ready(function() {
    if (Nimbus.Auth.authorized()) {
      foundry.init(function() {
        $('#loading').addClass('loaded');
        return $("#login_buttons").removeClass("redirect");
      });
    }
  });

  $(document).ready(function() {
    $('#google_login').on('click', function(evt) {
      if (!(localStorage["version"] === "google")) {
        localStorage["version"] = "google";
        window.location.reload();
      }
      return Nimbus.Auth.authorize('GDrive');
    });
    $('.logout_btn').on('click', function(evt) {
      foundry.logout();
      return location.reload();
    });
  });

}).call(this);
